//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Student()
        {
            this.T_SelectCourse = new HashSet<T_SelectCourse>();
        }
    
        public int SID { get; set; }
        public string StuNum { get; set; }
        public string StuName { get; set; }
        public string StuSex { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual T_SchoolInfo T_SchoolInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SelectCourse> T_SelectCourse { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
