//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Teacher
    {
        public int TID { get; set; }
        public Nullable<int> TeacherNum { get; set; }
        public string TeacherName { get; set; }
        public string TeacherSex { get; set; }
        public string ProfessionalTitle { get; set; }
        public string TeacherAbout { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
