//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Teacher()
        {
            this.T_Course = new HashSet<T_Course>();
        }
    
        public int TID { get; set; }
        public Nullable<int> TeacherNum { get; set; }
        public string TeacherName { get; set; }
        public string TeacherSex { get; set; }
        public string ProfessionalTitle { get; set; }
        public string TeacherAbout { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Course> T_Course { get; set; }
    }
}
