//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Video
    {
        public int VID { get; set; }
        public string VideoName { get; set; }
        public string VideoAbout { get; set; }
        public Nullable<System.DateTime> InitTime { get; set; }
        public string VideoID { get; set; }
        public Nullable<short> IsHaveExerc { get; set; }
        public Nullable<int> CourseID { get; set; }
    }
}
