//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Video()
        {
            this.T_Discuss = new HashSet<T_Discuss>();
            this.T_Exercises = new HashSet<T_Exercises>();
        }
    
        public int VID { get; set; }
        public string VideoName { get; set; }
        public string VideoAbout { get; set; }
        public Nullable<System.DateTime> InitTime { get; set; }
        public string VideoID { get; set; }
        public Nullable<short> IsHaveExerc { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual T_Course T_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Discuss> T_Discuss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Exercises> T_Exercises { get; set; }
    }
}
